#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$POSTGRES_DB" \ <<-EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$ETL_POSTGRES_USER') THEN
    CREATE ROLE $ETL_POSTGRES_USER LOGIN PASSWORD '$ETL_POSTGRES_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$ML_POSTGRES_USER') THEN
    CREATE ROLE $ML_POSTGRES_USER LOGIN PASSWORD '$ML_POSTGRES_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_POSTGRES_USER') THEN
    CREATE ROLE $APP_POSTGRES_USER LOGIN PASSWORD '$APP_POSTGRES_PASSWORD';
    END IF;

END
\$\$;
EOSQL